const ErrorCodeEnum = Object.freeze({
  CONFIRM_ACT_PWD: "CONFIRM_ACT_PWD",
  CONFIRM_TX_PWD: "CONFIRM_TX_PWD",
  USER_TYPE: "USER_TYPE",
  TWO_FACTOR_AUTH: "TWO_FACTOR_AUTH",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_APPROVAL: "ACCOUNT_APPROVAL",
});

module.exports = { ErrorCodeEnum };
